name: Deploy React docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - run: pnpm install
      name: Install dependencies
      
    - run: pnpm build-storybook
      name: Build Storybook

    - run: ls
      name: List directory
      
    - name: Deploy Storybook
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./storybook-static
