name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Build and deploy Storybook
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./storybook-static
