name: Publish Svelte library to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: 🚀 Publish Svelte library
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./svelte
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: pnpm install

      - name: Build and package
        run: pnpm package

      - name: 🚀 Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./svelte/package.json
          token: ${{ secrets.PUBLISH_NPM_GLYPHON_SVELTE }}
