name: Unit tests for Svelte library
on: pull_request

jobs:
  test:
    if: contains(github.ref, 'svelte-')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./svelte
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        name: Setup node.js
        with:
          node-version: "18"

      - run: pnpm install
        name: Install dependencies

      - run: pnpm package
        name: Check if build works
