name: Unit tests
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        name: Setup node.js
        with:
          node-version: "18"

      - run: pnpm install
        name: Install dependencies

      - run: pnpm test
        name: Run unit tests

      - run: pnpm build
        name: Check build
